# Generated by Django 5.0.6 on 2025-07-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.AddField(
            model_name='customuser',
            name='section',
            field=models.CharField(choices=[('Ages 13-15', 'Ages 13-15'), ('Ages 16-18', 'Ages 16-18'), ('UG/PG', 'UG/PG'), ('Professional', 'Professional')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
